"""
All user-facing message constants for Jirassic Pack CLI.
"""

SEE_NOBODY_CARES = "🦖 See, Nobody Cares."
ABORTED = "🦖 Aborted."
SUCCESS = "🦖 Success!"
FAILED_TO = "🦖 Failed to {action}: {error}"
WRITTEN_TO = "🦖 {item} written to {filename}"
NO_ISSUES_FOUND = "🦖 No issues found."
IS_REQUIRED = "is required."
INPUT_VALIDATION_ERROR = "Input validation error."
INVALID_INPUT = "Invalid input."
FILE_WRITE_ERROR = "🦖 Error writing file."
REPORT_WRITE_ERROR = "🦖 Error writing report."
ABORTED_USER_SELECTION = "🦖 Aborted user selection."
NO_VALID_USERS_SELECTED = "🦖 No valid users selected."
NO_WORKLOGS_FOUND = "🦖 No worklogs found."
NO_OVERDUE_ISSUES = "🦖 No overdue issues."
ALL_ISSUES_HAVE_WORKLOGS = "🦖 All issues have worklogs."
BULK_OPERATION_CANCELLED = "🦖 Bulk operation cancelled."
NO_ACTION_ITEMS = "🦖 No action items."
NO_NEXT_STEPS = "🦖 No next steps." 